spring:
  datasource:
    hikari:
      connection-timeout: 10000
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/sprello}
    username: ${DATABASE_USERRNAME:sprello_user}
    password: ${DATABASE_PASSWORD:sprello123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default-schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: sprello
server:
  servlet:
    context-path: /sprello

app:
  authorization-token:
    expiration-in-seconds: 600
    signature-key: dac1231R!@!R!@ACWKDP!K@K124210
