spring:
  datasource:
    hikari:
      connection-timeout: 10000
    url: jdbc:postgresql://localhost:5432/sprello
    username: sprello_user
    password: sprello123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default-schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: sprello
  mvc:
    locale: br
server:
  servlet:
    context-path: /sprello
