-- Role: sprello_user
CREATE ROLE sprello_user WITH
    LOGIN
    NOSUPERUSER
    INHERIT
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION
    ENCRYPTED PASSWORD 'md5d89f2e3d01dca83da7ac8eefee1edc70';

-- Database: sprello
CREATE DATABASE sprello
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.utf8'
    LC_CTYPE = 'en_US.utf8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

ALTER DEFAULT PRIVILEGES
    GRANT ALL ON TABLES TO postgres;

ALTER DEFAULT PRIVILEGES
    GRANT REFERENCES, DELETE, UPDATE, SELECT, INSERT ON TABLES TO sprello_user WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES
    GRANT ALL ON SEQUENCES TO postgres;

ALTER DEFAULT PRIVILEGES
    GRANT ALL ON SEQUENCES TO sprello_user;

ALTER DEFAULT PRIVILEGES
    GRANT EXECUTE ON FUNCTIONS TO postgres;

ALTER DEFAULT PRIVILEGES
    GRANT EXECUTE ON FUNCTIONS TO sprello_user;

ALTER DEFAULT PRIVILEGES
    GRANT EXECUTE ON FUNCTIONS TO PUBLIC;

ALTER DEFAULT PRIVILEGES
    GRANT USAGE ON TYPES TO postgres;

ALTER DEFAULT PRIVILEGES
    GRANT USAGE ON TYPES TO sprello_user;

ALTER DEFAULT PRIVILEGES
    GRANT USAGE ON TYPES TO PUBLIC;
